// Code generated by goagen v1.2.0, DO NOT EDIT.
//
// API "cellar": Application User Types
//
// Command:
// $ goagen
// --design=github.com/sssinsi/goa-sample/cellar/design
// --out=$(GOPATH)/src/github.com/sssinsi/goa-sample
// --version=v1.2.0

package app
